name: bucket_list_bliss
description: "BucketList Bliss: Capture and achieve your life's dreams and aspirations in a simple, motivating app. Your ultimate bliss, one tick at a time."
version: 0.0.1+1

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_hooks: ^0.20.3
  hooks_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  freezed_annotation: ^2.4.1

  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  build_runner: ^2.4.7
  flutter_lints: ^3.0.0
  custom_lint: ^0.6.4
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10
  import_sorter: ^4.6.0

flutter:
  uses-material-design: true

scripts:
  format: fvm flutter pub run import_sorter:main && fvm dart format lib
  fix:dry-run: fvm dart fix --dry-run lib
  fix:apply: fvm dart fix --apply lib
  analyze: fvm flutter analyze
  test: fvm flutter test lib
  generate: fvm flutter pub run build_runner build --delete-conflicting-outputs

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
