name: github pages deployment

on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  deploy:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Repository
        id: version
        run: |
          REPOSITORY=$(echo ${{ github.repository }} | sed -e "s#.*/##")
          echo ::set-output name=repository::$REPOSITORY

      - name: Set up Flutter
        uses: subosito/flutter-action@v2.16.0
        with:
          flutter-version: "3.19.5"
          channel: "stable"
          cache: true

      - name: Install packages
        run: flutter pub get

      - name: Build for web
        run: flutter build web --web-renderer html --base-href /${{ steps.version.outputs.repository }}/

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
